myproject/myapp/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include

import shora.views
from . import views
from .views import SignupView, verify_phone, user_login

urlpatterns = [

    path('login/', user_login, name='login'),
    path('singup/', SignupView.as_view(), name='singup'),

    path('logout', views.logout_view.as_view(), name='logout'),
    path("pannel/home/", views.home, name="home"),
    path('verify-phone/<int:user_id>/', verify_phone, name='verify_phone'),

    # آدرس برای ویو تأیید شماره تلفن
    path('pannel/profile/', views.profile, name='profile'),
    path('pannel/rules/', views.rules, name='rules'),
    path('pannel/about/', views.about, name='about'),
    path('pannel/contact-us/', views.contact_us, name='contact-us'),
    path('pannel/admin/payments/', views.payment_requests_list, name='payments'),
    path('pannel/submit-payment/', views.submit_payment, name='submit_payment'),
    path('pannel/admin/approve-payment/<int:payment_id>/', views.approve_payment, name='approve_payment'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'myproject'
urlpatterns = [
                  path('admin/', admin.site.urls, name='admin'),
                  path("", views.index, name="index"),
                  path("", include('myapp.urls')),
                  path("", include('shora.urls')),
                  path("", include('tickets.urls'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/shora/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'app1'
urlpatterns = [

                  path('pannel/council/<int:user_id>/', views.council, name='council'),
                  path('pannel/Assembly/<int:user_id>/', views.Assembly, name='assembly'),
                  path('pannel/council/success/', views.upload_document_success, name='upload_document_success')

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/tickets/urls.py
from django.urls import path
from . import views

app_name = 'tickets'
urlpatterns = [
    path('ticket/create/', views.create_ticket, name='create_ticket'),
    path('tickets/', views.ticket_list, name='ticket_list'),
    path('ticket/<int:ticket_id>/', views.ticket_detail, name='ticket_detail'),
    path('ticket/admin/', views.admin_dashboard, name='admin_dashboard'),
    path('ticket/admin/<int:ticket_id>/', views.respond_to_ticket, name='respond_to_ticket'),
]

myproject/myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import UserAccount
from persiantools.jdatetime import JalaliDate
from .models import Payment


class SignupForm(UserCreationForm):
    name = forms.CharField(label='نام')
    family = forms.CharField(label='نام خانوادگی')
    phone_number = forms.CharField(max_length=15, label='شماره تلفن')
    password1 = forms.CharField(widget=forms.PasswordInput(), label='پسورد')
    password2 = forms.CharField(widget=forms.PasswordInput(), label='تکرار پسورد')

    class Meta:
        model = UserAccount
        fields = ('name', 'family', 'phone_number', 'password1', 'password2')

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        if UserAccount.objects.filter(phone_number=phone_number).exists():
            raise forms.ValidationError("A user with this phone number already exists.")
        return phone_number


class PhoneVerificationForm(forms.Form):
    verification_code = forms.CharField(max_length=6, required=True, label='کد تأیید')


class LoginForm(forms.Form):
    phone_number = forms.CharField(max_length=15, label="شماره تلفن")
    password = forms.CharField(widget=forms.PasswordInput, label="رمز عبور")

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        # اگر نیاز به اعتبارسنجی خاصی دارید، اینجا اضافه کنید
        return phone_number


from django import forms
from django.contrib.auth.models import User


class CompleteProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(label="پروفایل")
    # فیلدی برای انتخاب تاریخ میلادی
    date = forms.DateField(
        widget=forms.DateInput(attrs={"type": "date"}),
        label="تاریخ میلادی"
    )

    id_card = forms.ImageField(label=" کارت ملی")
    selfie = forms.ImageField(label="عکس سلفی با کارت ملی")
    national_code = forms.CharField(label="کد ملی")

    # اضافه کردن فیلدهای پسورد
    password = forms.CharField(
        label="رمز عبور جدید",
        widget=forms.PasswordInput(attrs={'placeholder': 'رمز عبور جدید'}),
        required=False
    )
    password_confirm = forms.CharField(
        label="تایید رمز عبور",
        widget=forms.PasswordInput(attrs={'placeholder': 'تایید رمز عبور'}),
        required=False
    )

    class Meta:
        model = UserAccount  # یا User اگر از مدل پیش‌فرض Django استفاده می‌کنید
        fields = (
            'name', 'family', 'phone_number', 'birth_date', 'profile_picture', 'id_card', 'selfie', 'national_code',
            'password', 'password_confirm'
        )

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if password and password != password_confirm:
            raise forms.ValidationError("رمز عبور و تایید رمز عبور با هم تطابق ندارند.")

        return cleaned_data

    def clean_date(self):
        """
        این متد داده‌های واردشده را می‌گیرد و به شمسی تبدیل می‌کند.
        """
        date = self.cleaned_data['date']
        # تبدیل تاریخ میلادی به شمسی
        shamsi_date = JalaliDate.from_gregorian(gregorian_date=date).strftime('%Y/%m/%d')
        return shamsi_date





class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['amount', 'card_number','receipt_image']  # مشخصات فرم
        labels = {
            'amount': 'مبلغ پرداخت',  # تغییر نام فیلد به فارسی
            'card_number':'شماره کارت',
            'receipt_image': 'تصویر رسید پرداخت',  # تغییر نام فیلد به فارسی
        }


    def clean_amount(self):
        amount = self.cleaned_data.get('amount')
        if amount < 500000:
            raise forms.ValidationError('مبلغ پرداخت باید حداقل 500,000 تومان باشد.')
        return amount

myproject/myapp/views.py
from django.views import View
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib import messages
from .forms import SignupForm, LoginForm, CompleteProfileForm, PhoneVerificationForm,PaymentForm,Payment
from .models import UserAccount,Notification
from django.contrib.auth.decorators import login_required
import random
from .utils import send_verification_code  # فرض بر این است که تابع ارسال کد تأیید در اینجا قرار دارد
from django.contrib.auth import update_session_auth_hash
from tickets.models import Ticket
from shora.models import assembly,Document
from django.db.models import Q
from django.contrib.admin.views.decorators import staff_member_required




class SignupView(View):
    form_class = SignupForm
    initial = {}
    template_name = "loginorsingup/singup.html"

    def dispatch(self, request, *args, **kwargs):
        # اگر کاربر لاگین باشد، او را به صفحه پنل کاربری هدایت کن
        if request.user.is_authenticated:
            return redirect('home')  # 'user_panel' را با مسیر دلخواه جایگزین کنید
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)

            user.is_active = False
            user.save()

            # ذخیره شماره تلفن و ایجاد کد تأیید
            phone_number = form.cleaned_data.get('phone_number')
            verification_code = str(random.randint(100000, 999999))  # کد تأیید ۶ رقمی تصادفی

            user.phone_number = phone_number
            user.verification_code = verification_code
            user.save()

            # ارسال کد تأیید به شماره تلفن
            send_verification_code(phone_number, verification_code)

            messages.success(request, 'لطفاً شماره تلفن خود را تأیید کنید.')
            return redirect('verify_phone', user_id=user.id)  # هدایت کاربر به صفحه تأیید شماره تلفن

        return render(request, self.template_name, {'form': form})



def verify_phone(request, user_id):
    user = get_object_or_404(UserAccount, pk=user_id)

    if request.method == 'POST':
        form = PhoneVerificationForm(request.POST)
        if form.is_valid():
            verification_code = form.cleaned_data['verification_code']
            if user.verification_code == verification_code:
                user.is_phone_verified = True
                user.verification_code = None  # حذف کد تأیید بعد از تأیید
                user.save()

                # بعد از تایید شماره تلفن، حساب کاربری فعال می‌شود
                user.is_active = True
                user.save()

                messages.success(request, 'شماره تلفن شما با موفقیت تأیید شد.')
                return redirect('login')
            else:
                messages.error(request, 'کد تأیید اشتباه است. لطفاً دوباره تلاش کنید.')
    else:
        form = PhoneVerificationForm()

    return render(request, 'loginorsingup/verify_phone.html', {'form': form})


from django.shortcuts import redirect

def user_login(request):
    # اگر کاربر لاگین شده باشد، او را به صفحه پنل هدایت کن
    if request.user.is_authenticated:
        return redirect('home')  # 'user_panel' را با مسیر دلخواه جایگزین کنید

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            phone_number = form.cleaned_data['phone_number']
            password = form.cleaned_data['password']

            try:
                user = UserAccount.objects.get(phone_number=phone_number)
            except UserAccount.DoesNotExist:
                user = None

            if user is not None and user.check_password(password):
                if user.is_phone_verified and user.is_active:
                    auth_login(request, user)
                    return redirect('home')
                else:
                    messages.error(request, 'حساب کاربری شما فعال نشده است یا شماره تلفن تأیید نشده است.')
            else:
                messages.error(request, 'شماره تلفن یا رمز عبور اشتباه است.')

    else:
        form = LoginForm()

    return render(request, 'loginorsingup/login.html', {'form': form})



class logout_view(View):
    def get(self, request):
        request.session.clear()
        return redirect('login')

def update_user_verification(user):
    """
    بررسی و به‌روزرسانی وضعیت تأیید کاربر
    """
    if user.is_verified in ["1", "3"]:
        user.is_verified = "2"
    else:
        user.is_verified = "4"
    user.save()
def is_password_secure(password):
    """
    اعتبارسنجی رمز عبور
    بررسی طول رمز عبور و معیارهای امنیتی
    """
    if len(password) < 8:
        return False  # رمز عبور باید حداقل 8 کاراکتر باشد
    return True

@login_required
def profile(request):
    """
    View مربوط به پروفایل کاربری
    """
    if request.method == 'POST':
        form = CompleteProfileForm(request.POST, request.FILES, instance=request.user)

        if form.is_valid():
            # بررسی و به‌روزرسانی وضعیت تأیید
            update_user_verification(request.user)

            # بررسی تغییر رمز عبور
            password = form.cleaned_data.get('password')
            if password:
                if not is_password_secure(password):
                    form.add_error('password', 'رمز عبور باید حداقل ۸ کاراکتر باشد.')
                    return render(request, 'pannel/profile.html', {'form': form})

                request.user.set_password(password)  # به‌روزرسانی پسورد
                update_session_auth_hash(request, request.user)  # به‌روزرسانی سشن

            # ذخیره اطلاعات کاربری
            form.save()
            return redirect('profile')
    else:
        form = CompleteProfileForm(instance=request.user)

    return render(request, 'pannel/profile.html', {'form': form})


@login_required
def rules(request):
    return render(request, 'pannel/Rules/index.html')


@login_required
def about(request):
    return render(request, 'pannel/About/index.html')


@login_required
def contact_us(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')

        message = request.POST.get('message')

        # ارسال ایمیل
        # حذف شده

        messages.success(request, 'پیام شما با موفقیت ارسال شد.')
        return redirect('contact')  # بازگشت به صفحه تماس پس از ارسال موفق

    return render(request, 'pannel/contact_us/index.html')


def home(request):
    # تعداد قانونگذاران تأیید شده و رد شده
    approved_lawmakers = assembly.objects.filter(user=request.user, status='approved').count()
    rejected_lawmakers = assembly.objects.filter(user=request.user, status='rejected').count()

    # تعداد اسناد تأیید شده و رد شده
    approved_Document = assembly.objects.filter(user=request.user, status='approved').count()
    rejected_Document = assembly.objects.filter(user=request.user, status='rejected').count()

    # مجموع تأیید شده‌ها و رد شده‌ها
    total_approved = approved_lawmakers + approved_Document
    total_Document = rejected_lawmakers + rejected_Document

    # استفاده از message_type به جای is_public
    notifications = Notification.objects.filter(message_type='public')  # اعلان‌های عمومی
    # تعداد اعلان‌های خوانده نشده
    unread_notifications_count = Notification.objects.filter(users=request.user, is_read=False).count()
    notifications.update(is_read=True)

    # تعداد تیکت‌های باز مربوط به کاربر جاری
    tickets_count = Ticket.objects.filter(user=request.user).count()


    return render(request, 'pannel/home/index.html', {
        'approved_lawmakers': total_approved,
        'rejected_lawmakers': total_Document,
        'tickets_count': tickets_count,
        'notifications': notifications,
        'unread_notifications_count': unread_notifications_count,
        'user': request.user
    })


@staff_member_required
def payment_requests_list(request):
    # دریافت درخواست‌های تأیید نشده
    payments = Payment.objects.filter(is_approved=False).order_by('-id')
    return render(request, 'payment/payment_requests_list.html', {'payments': payments})

def submit_payment(request):
    if request.method == 'POST':
        print(request.POST)  # داده‌های ارسال‌شده از فرم
        form = PaymentForm(request.POST, request.FILES)
        if form.is_valid():
            card_number = request.POST.get('card_number')
            print(f"Card number: {card_number}")
            account = get_object_or_404(UserAccount, card_number=card_number)

            payment = form.save(commit=False)
            payment.account = account
            payment.save()

            messages.success(request, 'فیش شما با موفقیت ثبت شد. لطفاً منتظر تأیید ادمین باشید.')
            return redirect('submit_payment')
        else:
            print("Form errors:", form.errors)
    else:
        form = PaymentForm()

    return render(request, 'payment/submit_payment.html', {'form': form})

@staff_member_required
def approve_payment(request, payment_id):
    payment = get_object_or_404(Payment, id=payment_id, is_approved=False)
    payment.is_approved = True
    payment.account.balance += payment.amount  # شارژ حساب کاربر
    payment.account.save()
    payment.save()
    messages.success(request, f"پرداخت {payment.amount} برای {payment.account.phone_number} تأیید شد.")
    return redirect('payments')  # مسیر داشبورد ادمین

myproject/myapp/templates/pannel/compelet_profile.html
{% load jalali_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>تکمیل پروفایل</title>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>



    <style>
        body {
            font-family: "Roboto", sans-serif;
            margin: 0;
            text-align: center;
            padding: 0;
            background-color: #f4f4f4;
            direction: rtl;
            display: flex;
            height: 100vh;
            font-weight: bolder;

            box-sizing: border-box;
            justify-content: center;
            align-items: center;
        }

        label {

            position: relative;

        }

        input {
            padding: 0.5vw;
            width: 70%;
            text-align: right;
            margin-top: .5vw;
        }

        .sidebar {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            right: 0;
            background-color: #333;
            overflow-x: hidden;
            transition: 0.5s;
            padding-top: 60px;
            display: flex;
            flex-direction: column;
            align-items: flex-start;
            box-shadow: -2px 0 5px rgba(0, 0, 0, 0.5);
        }

        .sidebar a {
            padding: 15px 25px;
            text-decoration: none;
            font-size: 20px;
            color: #b8c1ec;
            display: flex;
            align-items: center;
            transition: 0.3s;
            text-align: right;
            width: 100%;
        }

        .sidebar a:hover {
            color: #f1f1f1;
            background-color: #444;
        }

        .sidebar ion-icon {
            margin-left: 10px;
            font-size: 24px;
        }

        .sidebar .closebtn {
            position: absolute;
            top: 10px;
            left: 15px;
            font-size: 36px;
            color: #b8c1ec;
            cursor: pointer;
        }

        .openbtn {
            font-size: 30px;
            cursor: pointer;
            background-color: #333;
            color: white;
            padding: 10px 15px;
            border: none;
            transition: 0.3s;

            position: fixed;
            top: 10px;
            right: 10px;
        }

        .openbtn:hover {
            background-color: #555;
        }

        #main {
            transition: margin-right .5s;
            padding: 16px;
            width: calc(100% - 250px); /* Adjust for sidebar width */
            box-sizing: border-box;
            margin-right: 0;
        }

        .profile-container {
            width: 100%;
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 20px;
            position: relative;

            box-sizing: border-box;
        }

        .profile {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
            width: 100%;
            max-width: 800px; /* Adjusted width for more fields */
            box-sizing: border-box;
        }

        .profile img {
            width: 80px; /* Adjusted size */
            height: 80px; /* Adjusted size */
            border-radius: 50%;
            margin-bottom: 10px;
            display: block;
            margin: 0 auto;
        }

        .profile h3 {
            margin: 5px 0;
            color: #333;
            text-align: center;
        }

        .profile-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 10px;
            margin-bottom: 10px;
        }

        .profile-item {
            display: flex;
            align-items: center;
            background-color: #f4f4f4;
            color: #333;
            padding: 10px;
            border-radius: 5px;
            width: 100%;
            box-sizing: border-box;
        }

        .profile-item ion-icon {
            margin-left: 10px;
            color: #333;
        }

        .profile-item input {
            border: none;
            background: none;
            color: #333;
            width: 100%;
            font-size: 16px;
            outline: none;
            text-align: right;
        }

        .profile-item img {
            max-width: 100px;
            max-height: 100px;
            object-fit: cover;
            border-radius: 5px;
        }

        .edit-button {
            margin-top: 10px;
            background-color: #333;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
            width: 100%;
            text-align: center;
        }

        .edit-button:hover {
            background-color: #555;
        }

        .profilemen img {
            width: 40px;
            height: 40px;
            border-radius: 50%;
            margin-left: 10px;
        }

        .profilemen:hover {
            color: #f1f1f1;
            background-color: #444;
        }

        .selfie-instruction {
            background-color: #f9f9f9;
            border: 1px solid #ddd;
            padding: 15px;
            margin-top: 20px;
            border-radius: 8px;
            text-align: right;
        }

        .selfie-instruction h4 {
            font-size: 18px;
            margin-bottom: 10px;
            color: #333;
        }

        .selfie-instruction p {
            font-size: 16px;
            color: #555;
            line-height: 1.6;
            margin-bottom: 10px;
        }

        .selfie-instruction blockquote {
            font-size: 18px;
            font-weight: bold;
            color: #222;
            background-color: #eee;
            padding: 10px;
            border-left: 5px solid #ccc;
            margin-bottom: 10px;
            text-align: center;
        }

        .selfie-instruction blockquote p {
            margin: 0;
        }

        .selfie-instruction p:last-child {
            margin-bottom: 0;
        }


        @media screen and (max-height: 450px) {
            .sidebar {
                padding-top: 15px;
            }

            .sidebar a {
                font-size: 18px;
            }
        }

        @media screen and (max-width: 768px) {
            .sidebar {
                width: 100%;
                height: 100%;
            }

            #main {
                width: 100%;
            }

            .openbtn {
                position: fixed;
                right: 10px;
                top: 10px;
                z-index: 2;
            }
        }
    </style>
</head>
<body>
{% include 'pannel/menu.html' %}

<div class="profile-container">
    <div class="profile">
        <h3>تکمیل پروفایل</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table class="form-table" style="width: 100%;">
                {{ form.as_table }}

            </table>

            <!-- اضافه کردن توضیحات مربوط به عکس سلفی -->
            <div class="selfie-instruction">
                <h4>راهنمای ارسال عکس سلفی</h4>
                <p>لطفاً یک عکس سلفی از خودتان بگیرید و در دستتان یک کاغذ و کارت ملی نگه دارید که روی آن نوشته شده
                    باشد:</p>
                <blockquote>
                    <p>«من با رضایت کامل در این سامانه ثبت‌نام کرده‌ام.»</p>
                </blockquote>
                <p>این عکس برای تایید هویت شما مورد نیاز است. توجه داشته باشید که چهره و نوشته باید به وضوح قابل مشاهده
                    باشند.</p>
            </div>

            <button type="submit" class="edit-button">ذخیره تغییرات</button>
        </form>
    </div>
</div>


<script>
    function openNav() {
        document.getElementById("sidebar").style.width = "250px";
        document.getElementById("main").style.marginRight = "250px";
    }

    function closeNav() {
        document.getElementById("sidebar").style.width = "0";
        document.getElementById("main").style.marginRight = "0";
    }

</script>


</body>
</html>

myproject/myapp/templates/pannel/menu.html
{% load static %}
<!-- دکمه باز و بسته کردن اسلایدبار -->
<button class="sidebar-toggle" onclick="toggleSidebar()">
    <i class="icon ion-md-menu"></i>
</button>

<!-- اسلایدبار -->
<aside class="sidebar" id="sidebar">
    <!-- عکس پروفایل -->
    <div class="profile-pic">
        {% if user.profile_picture %}
            <img src="{{ user.profile_picture.url }}" alt="Profile Picture">
        {% else %}
            <img src="{% static 'images/profile-avatar-66.png' %}" alt="Default Profile Picture">
        {% endif %}
    </div>
    <h2>{{ user.name }} {{ user.family }}</h2>
    <!-- نمایش موجودی حساب -->
    <div class="account-balance">
        <span>موجودی حساب: </span>
        <strong>{{ user.balance|floatformat:0 }} تومان</strong>
        <!-- فرض کردیم که useraccount موجودی را ذخیره می‌کند -->
    </div>
    <ul>
        <li>
            <a href="{% url 'home' %}">
                <i class="icon ion-md-home"></i>
                <span>پیشخوان</span>
            </a>
        </li>
        <li>
            <a href="{% url 'profile' %}">
                <i class="icon ion-md-person"></i>
                <span>پروفایل من</span>
            </a>
        </li>

        <li>
            <a href="{% url 'app1:council' user_id=user.id %}">
                <i class="icon ion-md-mail"></i>
                <span>لایحه نویسی برای شورا</span>
            </a>
        </li>
        <li>
            <a href="{% url 'app1:assembly' user_id=user.id %}" disabled="True">
                <i class="icon ion-md-mail"></i>
                <span>لایحه نویسی برای مجلس</span>
            </a>
        </li>
        <li>
            <a href="{% url 'tickets:ticket_list' %}">
                <i class="icon ion-md-mail"></i>
                <span>تیکت</span>
            </a>
        </li>
        <li>
            <a href="{% url 'submit_payment' %}">
                <i class="icon ion-md-wallet"></i>
                <span>شارژ حساب</span>
            </a>
        </li>


        {% if user.is_staff %}

            <hr>

            <!-- بخش‌های مخصوص ادمین -->
            <li>
                <a href="../admin">
                    <i class="icon ion-md-speedometer"></i>
                    <span>داشبورد ادمین</span>
                </a>
            </li>
            <li>

            <li>
                <a href="{% url 'tickets:admin_dashboard' %}">
                    <i class="icon ion-md-stats"></i>
                    <span>گزارش‌ها</span>
                </a>
            </li>
            <li>
                <a href="{% url 'payments' %}">
                    <i class="icon ion-md-clipboard"></i>
                    <span>رسید ها</span>
                </a>
            </li>

        {% endif %}
        <hr>
        <li>
            <a href="{% url 'logout' %}" style="color: lightpink;">
                <i class="icon ion-md-log-out"></i>
                <span>خروج</span>
            </a>
        </li>
    </ul>
</aside>

<!-- استایل‌ها و اسکریپت باقی می‌مانند بدون تغییر -->


<!-- استایل‌های مربوط به اسلایدبار -->
<style>
    body {
        font-family: Arial, sans-serif;
        direction: rtl;
        text-align: right;
        margin: 0;
        padding: 0;
    }

    .sidebar {
        width: 250px;
        background-color: #2d3436;
        color: #fff;
        display: flex;
        flex-direction: column;
        align-items: center;
        padding-top: 20px;
        position: fixed;
        height: 100%;
        transition: transform 0.3s ease-in-out;
        z-index: 2;
    }

    .sidebar h2 {
        margin-bottom: 30px;
    }

    .profile-pic {
        width: 100px;
        height: 100px;
        border-radius: 50%;
        background-color: #dfe6e9;
        overflow: hidden;
        margin-bottom: 20px;
    }

    .profile-pic img {
        width: 100%;
        height: 100%;
        object-fit: cover;

    }

    .account-balance {


        color: #ffffff;
        text-align: center;
    }

    .account-balance strong {

        color: #00b894; /* رنگ سبز برای مبلغ */
    }

    .sidebar ul {
        list-style: none;
        width: 100%;
    }

    .sidebar ul li a {
        padding: 15px 20px;
        display: flex;
        align-items: center;
        cursor: pointer;
        border-bottom: 1px solid #3d3d3d;
        transition: background 0.3s;
        text-decoration: none;
        color: white;
        font-weight: 600;
    }

    .sidebar ul li:hover {
        background-color: #636e72;
        margin-right: 0.2vw;
        transition: 0.4s;
        border-radius: 0.2vw;

    }

    .sidebar ul li i {
        font-size: 20px;
        margin-left: 10px;
    }

    .sidebar ul li span {
        flex: 1;
    }

    /* دکمه برای بستن اسلایدبار */
    .sidebar-toggle {
        display: none;
    }

    @media (max-width: 992px) {

        .sidebar {
            transform: translateX(100%);
        }

        .sidebar-toggle {
            display: block;
            position: fixed;
            top: 20px;
            right: 20px;
            background-color: #2d3436;
            color: #fff;
            border: none;
            padding: 10px;
            border-radius: 50%;
            z-index: 3;
            font-size: 20px;
            cursor: pointer;
        }

        .sidebar.open {
            transform: translateX(0);
        }
    }

    @media (max-width: 768px) {


        .sidebar-toggle {
            display: block;
            position: fixed;
            top: 20px;
            right: 20px;
            background-color: #2d3436;
            color: #fff;
            border: none;
            font-size: 20px;
            padding: 10px;
            border-radius: 50%;
            z-index: 3;
            cursor: pointer;
        }

        .sidebar.open {
            transform: translateX(0);
        }
    }
</style>

<!-- اسکریپت برای باز و بسته کردن اسلایدبار -->
<script>
    function toggleSidebar() {
        const sidebar = document.getElementById('sidebar');
        sidebar.classList.toggle('open');
    }
</script>

myproject/myapp/templates/pannel/password_change_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!-- password_change_done.html -->
<h2>پسورد شما با موفقیت تغییر کرد!</h2>
</body>
</html>